CREATE DATABASE IF NOT EXISTS la_verdad
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE la_verdad;

CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre_usuario VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    es_admin BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Articulos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    tipo ENUM('noticia', 'edicto') NOT NULL,
    titulo VARCHAR(255) NOT NULL,
    subtitulo VARCHAR(500) NULL,
    imagen VARCHAR(500) NULL,
    contenido TEXT NULL,
    dias INT NOT NULL DEFAULT 0,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS diarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    archivo VARCHAR(500) NOT NULL,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
