USE la_verdad;

ALTER TABLE Articulos
ADD COLUMN IF NOT EXISTS dias INT NOT NULL DEFAULT 0 AFTER contenido;

CREATE TABLE IF NOT EXISTS diarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATE NOT NULL UNIQUE,
    archivo VARCHAR(500) NOT NULL,
    creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
